project.version=${project.version}
release.lab=${release.lab}
lab01.version=${lab01.version}
lab02.version=${lab02.version}
lab03.version=${lab03.version}
lab04.version=${lab04.version}
lab05.version=${lab05.version}
